/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package check;

/**
 *
 * @author 203
 */
public class I1 extends javax.swing.JFrame {

    /**
     * Creates new form I1
     */
    public I1() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        I1 = new javax.swing.JLabel();
        retina = new javax.swing.JButton();
        huella = new javax.swing.JButton();
        cedula = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        I1.setForeground(I1.getBackground());
        I1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/M1.jpg"))); // NOI18N
        getContentPane().add(I1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        retina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retinaActionPerformed(evt);
            }
        });
        getContentPane().add(retina, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 500, 45, 30));

        huella.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                huellaActionPerformed(evt);
            }
        });
        getContentPane().add(huella, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, 45, 27));

        cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedulaActionPerformed(evt);
            }
        });
        getContentPane().add(cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 570, 45, 24));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedulaActionPerformed
        new I4().setVisible(true);
    }//GEN-LAST:event_cedulaActionPerformed

    private void retinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retinaActionPerformed
        new I3().setVisible(true);
    }//GEN-LAST:event_retinaActionPerformed

    private void huellaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_huellaActionPerformed
        new I2().setVisible(true);
    }//GEN-LAST:event_huellaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(I1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(I1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(I1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(I1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new I1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel I1;
    private javax.swing.JButton cedula;
    private javax.swing.JButton huella;
    private javax.swing.JButton retina;
    // End of variables declaration//GEN-END:variables
}
